version: '3'
services: 
    db:
        image: mysql
        ports: 
            - 3306:3306
        environment: 
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: lms
            MYSQL_USER: lms
            MYSQL_PASSWORD: lms
    web:
        build: .
        depends_on:
            - db
        environment: 
            HOSTNAME: db
        ports:
        - 8080:8080
